//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.04 at 10:22:31 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/nomina", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.sat.gob.mx/nomina", prefix = "nomina")
})
package mx.gob.sat.cfd.bindings.nomina11;
