//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 11:48:07 PM CDT 
//


package mx.gob.sat.cfd.bindings.notariospublicos;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfd.bindings.notariospublicos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfd.bindings.notariospublicos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotariosPublicos }
     * 
     */
    public NotariosPublicos createNotariosPublicos() {
        return new NotariosPublicos();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosAdquiriente }
     * 
     */
    public NotariosPublicos.DatosAdquiriente createNotariosPublicosDatosAdquiriente() {
        return new NotariosPublicos.DatosAdquiriente();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosAdquiriente.DatosAdquirientesCopSC }
     * 
     */
    public NotariosPublicos.DatosAdquiriente.DatosAdquirientesCopSC createNotariosPublicosDatosAdquirienteDatosAdquirientesCopSC() {
        return new NotariosPublicos.DatosAdquiriente.DatosAdquirientesCopSC();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosEnajenante }
     * 
     */
    public NotariosPublicos.DatosEnajenante createNotariosPublicosDatosEnajenante() {
        return new NotariosPublicos.DatosEnajenante();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosEnajenante.DatosEnajenantesCopSC }
     * 
     */
    public NotariosPublicos.DatosEnajenante.DatosEnajenantesCopSC createNotariosPublicosDatosEnajenanteDatosEnajenantesCopSC() {
        return new NotariosPublicos.DatosEnajenante.DatosEnajenantesCopSC();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DescInmuebles }
     * 
     */
    public NotariosPublicos.DescInmuebles createNotariosPublicosDescInmuebles() {
        return new NotariosPublicos.DescInmuebles();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosOperacion }
     * 
     */
    public NotariosPublicos.DatosOperacion createNotariosPublicosDatosOperacion() {
        return new NotariosPublicos.DatosOperacion();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosNotario }
     * 
     */
    public NotariosPublicos.DatosNotario createNotariosPublicosDatosNotario() {
        return new NotariosPublicos.DatosNotario();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosAdquiriente.DatosUnAdquiriente }
     * 
     */
    public NotariosPublicos.DatosAdquiriente.DatosUnAdquiriente createNotariosPublicosDatosAdquirienteDatosUnAdquiriente() {
        return new NotariosPublicos.DatosAdquiriente.DatosUnAdquiriente();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosAdquiriente.DatosAdquirientesCopSC.DatosAdquirienteCopSC }
     * 
     */
    public NotariosPublicos.DatosAdquiriente.DatosAdquirientesCopSC.DatosAdquirienteCopSC createNotariosPublicosDatosAdquirienteDatosAdquirientesCopSCDatosAdquirienteCopSC() {
        return new NotariosPublicos.DatosAdquiriente.DatosAdquirientesCopSC.DatosAdquirienteCopSC();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosEnajenante.DatosUnEnajenante }
     * 
     */
    public NotariosPublicos.DatosEnajenante.DatosUnEnajenante createNotariosPublicosDatosEnajenanteDatosUnEnajenante() {
        return new NotariosPublicos.DatosEnajenante.DatosUnEnajenante();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DatosEnajenante.DatosEnajenantesCopSC.DatosEnajenanteCopSC }
     * 
     */
    public NotariosPublicos.DatosEnajenante.DatosEnajenantesCopSC.DatosEnajenanteCopSC createNotariosPublicosDatosEnajenanteDatosEnajenantesCopSCDatosEnajenanteCopSC() {
        return new NotariosPublicos.DatosEnajenante.DatosEnajenantesCopSC.DatosEnajenanteCopSC();
    }

    /**
     * Create an instance of {@link NotariosPublicos.DescInmuebles.DescInmueble }
     * 
     */
    public NotariosPublicos.DescInmuebles.DescInmueble createNotariosPublicosDescInmueblesDescInmueble() {
        return new NotariosPublicos.DescInmuebles.DescInmueble();
    }

}
