//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.04 at 10:22:11 PM CDT 
//


package mx.gob.sat.cfd.bindings.obrasarteantiguedades;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" /&gt;
 *       &lt;attribute name="TipoBien" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.sat.gob.mx/arteantiguedades}c_TipoBien"&gt;
 *             &lt;length value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="OtrosTipoBien"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="255"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="TituloAdquirido" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.sat.gob.mx/arteantiguedades}c_Tituloadquirido"&gt;
 *             &lt;length value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="OtrosTituloAdquirido"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="255"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Subtotal" type="{http://www.sat.gob.mx/arteantiguedades}t_Importe" /&gt;
 *       &lt;attribute name="IVA" type="{http://www.sat.gob.mx/arteantiguedades}t_Importe" /&gt;
 *       &lt;attribute name="FechaAdquisicion" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date"&gt;
 *             &lt;whiteSpace value="collapse"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="CaracterísticasDeObraoPieza" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.sat.gob.mx/arteantiguedades}c_CaracterísticasDeObraoPieza"&gt;
 *             &lt;length value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "obrasarteantiguedades")
public class Obrasarteantiguedades
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "TipoBien", required = true)
    protected String tipoBien;
    @XmlAttribute(name = "OtrosTipoBien")
    protected String otrosTipoBien;
    @XmlAttribute(name = "TituloAdquirido", required = true)
    protected String tituloAdquirido;
    @XmlAttribute(name = "OtrosTituloAdquirido")
    protected String otrosTituloAdquirido;
    @XmlAttribute(name = "Subtotal")
    protected BigDecimal subtotal;
    @XmlAttribute(name = "IVA")
    protected BigDecimal iva;
    @XmlAttribute(name = "FechaAdquisicion", required = true)
    protected XMLGregorianCalendar fechaAdquisicion;
    @XmlAttribute(name = "Caracter\u00edsticasDeObraoPieza", required = true)
    protected String característicasDeObraoPieza;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the tipoBien property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoBien() {
        return tipoBien;
    }

    /**
     * Sets the value of the tipoBien property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoBien(String value) {
        this.tipoBien = value;
    }

    /**
     * Gets the value of the otrosTipoBien property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtrosTipoBien() {
        return otrosTipoBien;
    }

    /**
     * Sets the value of the otrosTipoBien property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtrosTipoBien(String value) {
        this.otrosTipoBien = value;
    }

    /**
     * Gets the value of the tituloAdquirido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTituloAdquirido() {
        return tituloAdquirido;
    }

    /**
     * Sets the value of the tituloAdquirido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTituloAdquirido(String value) {
        this.tituloAdquirido = value;
    }

    /**
     * Gets the value of the otrosTituloAdquirido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtrosTituloAdquirido() {
        return otrosTituloAdquirido;
    }

    /**
     * Sets the value of the otrosTituloAdquirido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtrosTituloAdquirido(String value) {
        this.otrosTituloAdquirido = value;
    }

    /**
     * Gets the value of the subtotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * Sets the value of the subtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubtotal(BigDecimal value) {
        this.subtotal = value;
    }

    /**
     * Gets the value of the iva property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIVA() {
        return iva;
    }

    /**
     * Sets the value of the iva property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIVA(BigDecimal value) {
        this.iva = value;
    }

    /**
     * Gets the value of the fechaAdquisicion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaAdquisicion() {
        return fechaAdquisicion;
    }

    /**
     * Sets the value of the fechaAdquisicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaAdquisicion(XMLGregorianCalendar value) {
        this.fechaAdquisicion = value;
    }

    /**
     * Gets the value of the característicasDeObraoPieza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaracterísticasDeObraoPieza() {
        return característicasDeObraoPieza;
    }

    /**
     * Sets the value of the característicasDeObraoPieza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaracterísticasDeObraoPieza(String value) {
        this.característicasDeObraoPieza = value;
    }

}
