//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.25 at 03:58:30 PM CST 
//


package mx.gob.sat.cfd.bindings.renovacionysustitucionvehiculos;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DecretoRenovVehicular" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VehiculosUsadosEnajenadoPermAlFab" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="PrecioVehUsado" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_Importe" /&gt;
 *                           &lt;attribute name="TipoVeh" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_TipoVehiculo_r" /&gt;
 *                           &lt;attribute name="Marca" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="50"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="TipooClase" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="50"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Año" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                 &lt;minInclusive value="1900"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Modelo"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NIV"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="17"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumSerie"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="17"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumPlacas" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="10"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumMotor"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="17"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumFolTarjCir" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="40"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumPedIm"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="40"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Aduana"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="FechaRegulVeh" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                           &lt;attribute name="Foliofiscal" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="36"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="VehiculoNuvoSemEnajenadoFabAlPerm"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Año" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                 &lt;minInclusive value="1900"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Modelo"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumPlacas" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="10"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="RFC" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_RFC" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="VehEnaj" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_VehiculoEnajenado" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DecretoSustitVehicular" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VehiculoUsadoEnajenadoPermAlFab"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="PrecioVehUsado" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_Importe" /&gt;
 *                           &lt;attribute name="TipoVeh" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_TipoVehiculo_s" /&gt;
 *                           &lt;attribute name="Marca" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="50"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="TipooClase" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="50"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Año" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                 &lt;minInclusive value="1900"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Modelo"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NIV"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="17"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumSerie"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="17"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumPlacas" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="10"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumMotor"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="17"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumFolTarjCir" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="40"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumFolAvisoint" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="20"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumPedIm" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="40"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Aduana" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="FechaRegulVeh" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                           &lt;attribute name="Foliofiscal" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="36"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="VehiculoNuvoSemEnajenadoFabAlPerm"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Año" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                 &lt;minInclusive value="1900"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Modelo"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="NumPlacas" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="10"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="RFC" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_RFC" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="VehEnaj" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_VehiculoEnajenado" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Version" use="required" fixed="1.0"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;whiteSpace value="collapse"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="TipoDeDecreto" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_TipoDecreto" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "decretoRenovVehicular",
    "decretoSustitVehicular"
})
@XmlRootElement(name = "renovacionysustitucionvehiculos")
public class Renovacionysustitucionvehiculos
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DecretoRenovVehicular")
    protected Renovacionysustitucionvehiculos.DecretoRenovVehicular decretoRenovVehicular;
    @XmlElement(name = "DecretoSustitVehicular")
    protected Renovacionysustitucionvehiculos.DecretoSustitVehicular decretoSustitVehicular;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "TipoDeDecreto", required = true)
    protected String tipoDeDecreto;

    /**
     * Gets the value of the decretoRenovVehicular property.
     * 
     * @return
     *     possible object is
     *     {@link Renovacionysustitucionvehiculos.DecretoRenovVehicular }
     *     
     */
    public Renovacionysustitucionvehiculos.DecretoRenovVehicular getDecretoRenovVehicular() {
        return decretoRenovVehicular;
    }

    /**
     * Sets the value of the decretoRenovVehicular property.
     * 
     * @param value
     *     allowed object is
     *     {@link Renovacionysustitucionvehiculos.DecretoRenovVehicular }
     *     
     */
    public void setDecretoRenovVehicular(Renovacionysustitucionvehiculos.DecretoRenovVehicular value) {
        this.decretoRenovVehicular = value;
    }

    /**
     * Gets the value of the decretoSustitVehicular property.
     * 
     * @return
     *     possible object is
     *     {@link Renovacionysustitucionvehiculos.DecretoSustitVehicular }
     *     
     */
    public Renovacionysustitucionvehiculos.DecretoSustitVehicular getDecretoSustitVehicular() {
        return decretoSustitVehicular;
    }

    /**
     * Sets the value of the decretoSustitVehicular property.
     * 
     * @param value
     *     allowed object is
     *     {@link Renovacionysustitucionvehiculos.DecretoSustitVehicular }
     *     
     */
    public void setDecretoSustitVehicular(Renovacionysustitucionvehiculos.DecretoSustitVehicular value) {
        this.decretoSustitVehicular = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the tipoDeDecreto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDeDecreto() {
        return tipoDeDecreto;
    }

    /**
     * Sets the value of the tipoDeDecreto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDeDecreto(String value) {
        this.tipoDeDecreto = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VehiculosUsadosEnajenadoPermAlFab" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="PrecioVehUsado" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_Importe" /&gt;
     *                 &lt;attribute name="TipoVeh" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_TipoVehiculo_r" /&gt;
     *                 &lt;attribute name="Marca" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="50"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="TipooClase" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="50"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Año" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                       &lt;minInclusive value="1900"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Modelo"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NIV"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="17"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumSerie"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="17"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumPlacas" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="10"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumMotor"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="17"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumFolTarjCir" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="40"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumPedIm"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="40"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Aduana"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="FechaRegulVeh" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                 &lt;attribute name="Foliofiscal" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="36"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="VehiculoNuvoSemEnajenadoFabAlPerm"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Año" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                       &lt;minInclusive value="1900"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Modelo"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumPlacas" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="10"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="RFC" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_RFC" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="VehEnaj" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_VehiculoEnajenado" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vehiculosUsadosEnajenadoPermAlFab",
        "vehiculoNuvoSemEnajenadoFabAlPerm"
    })
    public static class DecretoRenovVehicular
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "VehiculosUsadosEnajenadoPermAlFab", required = true)
        protected List<Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculosUsadosEnajenadoPermAlFab> vehiculosUsadosEnajenadoPermAlFab;
        @XmlElement(name = "VehiculoNuvoSemEnajenadoFabAlPerm", required = true)
        protected Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculoNuvoSemEnajenadoFabAlPerm vehiculoNuvoSemEnajenadoFabAlPerm;
        @XmlAttribute(name = "VehEnaj", required = true)
        protected String vehEnaj;

        /**
         * Gets the value of the vehiculosUsadosEnajenadoPermAlFab property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vehiculosUsadosEnajenadoPermAlFab property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVehiculosUsadosEnajenadoPermAlFab().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculosUsadosEnajenadoPermAlFab }
         * 
         * 
         */
        public List<Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculosUsadosEnajenadoPermAlFab> getVehiculosUsadosEnajenadoPermAlFab() {
            if (vehiculosUsadosEnajenadoPermAlFab == null) {
                vehiculosUsadosEnajenadoPermAlFab = new ArrayList<Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculosUsadosEnajenadoPermAlFab>();
            }
            return this.vehiculosUsadosEnajenadoPermAlFab;
        }

        /**
         * Gets the value of the vehiculoNuvoSemEnajenadoFabAlPerm property.
         * 
         * @return
         *     possible object is
         *     {@link Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculoNuvoSemEnajenadoFabAlPerm }
         *     
         */
        public Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculoNuvoSemEnajenadoFabAlPerm getVehiculoNuvoSemEnajenadoFabAlPerm() {
            return vehiculoNuvoSemEnajenadoFabAlPerm;
        }

        /**
         * Sets the value of the vehiculoNuvoSemEnajenadoFabAlPerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculoNuvoSemEnajenadoFabAlPerm }
         *     
         */
        public void setVehiculoNuvoSemEnajenadoFabAlPerm(Renovacionysustitucionvehiculos.DecretoRenovVehicular.VehiculoNuvoSemEnajenadoFabAlPerm value) {
            this.vehiculoNuvoSemEnajenadoFabAlPerm = value;
        }

        /**
         * Gets the value of the vehEnaj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVehEnaj() {
            return vehEnaj;
        }

        /**
         * Sets the value of the vehEnaj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVehEnaj(String value) {
            this.vehEnaj = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Año" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *             &lt;minInclusive value="1900"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Modelo"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumPlacas" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="10"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="RFC" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_RFC" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VehiculoNuvoSemEnajenadoFabAlPerm
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "A\u00f1o", required = true)
            protected int año;
            @XmlAttribute(name = "Modelo")
            protected String modelo;
            @XmlAttribute(name = "NumPlacas", required = true)
            protected String numPlacas;
            @XmlAttribute(name = "RFC")
            protected String rfc;

            /**
             * Gets the value of the año property.
             * 
             */
            public int getAño() {
                return año;
            }

            /**
             * Sets the value of the año property.
             * 
             */
            public void setAño(int value) {
                this.año = value;
            }

            /**
             * Gets the value of the modelo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModelo() {
                return modelo;
            }

            /**
             * Sets the value of the modelo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModelo(String value) {
                this.modelo = value;
            }

            /**
             * Gets the value of the numPlacas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumPlacas() {
                return numPlacas;
            }

            /**
             * Sets the value of the numPlacas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumPlacas(String value) {
                this.numPlacas = value;
            }

            /**
             * Gets the value of the rfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRFC() {
                return rfc;
            }

            /**
             * Sets the value of the rfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRFC(String value) {
                this.rfc = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="PrecioVehUsado" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_Importe" /&gt;
         *       &lt;attribute name="TipoVeh" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_TipoVehiculo_r" /&gt;
         *       &lt;attribute name="Marca" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="50"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="TipooClase" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="50"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Año" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *             &lt;minInclusive value="1900"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Modelo"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NIV"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="17"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumSerie"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="17"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumPlacas" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="10"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumMotor"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="17"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumFolTarjCir" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="40"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumPedIm"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="40"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Aduana"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="FechaRegulVeh" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *       &lt;attribute name="Foliofiscal" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="36"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VehiculosUsadosEnajenadoPermAlFab
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "PrecioVehUsado", required = true)
            protected BigDecimal precioVehUsado;
            @XmlAttribute(name = "TipoVeh", required = true)
            protected String tipoVeh;
            @XmlAttribute(name = "Marca", required = true)
            protected String marca;
            @XmlAttribute(name = "TipooClase", required = true)
            protected String tipooClase;
            @XmlAttribute(name = "A\u00f1o", required = true)
            protected int año;
            @XmlAttribute(name = "Modelo")
            protected String modelo;
            @XmlAttribute(name = "NIV")
            protected String niv;
            @XmlAttribute(name = "NumSerie")
            protected String numSerie;
            @XmlAttribute(name = "NumPlacas", required = true)
            protected String numPlacas;
            @XmlAttribute(name = "NumMotor")
            protected String numMotor;
            @XmlAttribute(name = "NumFolTarjCir", required = true)
            protected String numFolTarjCir;
            @XmlAttribute(name = "NumPedIm")
            protected String numPedIm;
            @XmlAttribute(name = "Aduana")
            protected String aduana;
            @XmlAttribute(name = "FechaRegulVeh")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaRegulVeh;
            @XmlAttribute(name = "Foliofiscal", required = true)
            protected String foliofiscal;

            /**
             * Gets the value of the precioVehUsado property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPrecioVehUsado() {
                return precioVehUsado;
            }

            /**
             * Sets the value of the precioVehUsado property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPrecioVehUsado(BigDecimal value) {
                this.precioVehUsado = value;
            }

            /**
             * Gets the value of the tipoVeh property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoVeh() {
                return tipoVeh;
            }

            /**
             * Sets the value of the tipoVeh property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoVeh(String value) {
                this.tipoVeh = value;
            }

            /**
             * Gets the value of the marca property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMarca() {
                return marca;
            }

            /**
             * Sets the value of the marca property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMarca(String value) {
                this.marca = value;
            }

            /**
             * Gets the value of the tipooClase property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipooClase() {
                return tipooClase;
            }

            /**
             * Sets the value of the tipooClase property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipooClase(String value) {
                this.tipooClase = value;
            }

            /**
             * Gets the value of the año property.
             * 
             */
            public int getAño() {
                return año;
            }

            /**
             * Sets the value of the año property.
             * 
             */
            public void setAño(int value) {
                this.año = value;
            }

            /**
             * Gets the value of the modelo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModelo() {
                return modelo;
            }

            /**
             * Sets the value of the modelo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModelo(String value) {
                this.modelo = value;
            }

            /**
             * Gets the value of the niv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNIV() {
                return niv;
            }

            /**
             * Sets the value of the niv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNIV(String value) {
                this.niv = value;
            }

            /**
             * Gets the value of the numSerie property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumSerie() {
                return numSerie;
            }

            /**
             * Sets the value of the numSerie property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumSerie(String value) {
                this.numSerie = value;
            }

            /**
             * Gets the value of the numPlacas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumPlacas() {
                return numPlacas;
            }

            /**
             * Sets the value of the numPlacas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumPlacas(String value) {
                this.numPlacas = value;
            }

            /**
             * Gets the value of the numMotor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumMotor() {
                return numMotor;
            }

            /**
             * Sets the value of the numMotor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumMotor(String value) {
                this.numMotor = value;
            }

            /**
             * Gets the value of the numFolTarjCir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumFolTarjCir() {
                return numFolTarjCir;
            }

            /**
             * Sets the value of the numFolTarjCir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumFolTarjCir(String value) {
                this.numFolTarjCir = value;
            }

            /**
             * Gets the value of the numPedIm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumPedIm() {
                return numPedIm;
            }

            /**
             * Sets the value of the numPedIm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumPedIm(String value) {
                this.numPedIm = value;
            }

            /**
             * Gets the value of the aduana property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAduana() {
                return aduana;
            }

            /**
             * Sets the value of the aduana property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAduana(String value) {
                this.aduana = value;
            }

            /**
             * Gets the value of the fechaRegulVeh property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFechaRegulVeh() {
                return fechaRegulVeh;
            }

            /**
             * Sets the value of the fechaRegulVeh property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFechaRegulVeh(XMLGregorianCalendar value) {
                this.fechaRegulVeh = value;
            }

            /**
             * Gets the value of the foliofiscal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFoliofiscal() {
                return foliofiscal;
            }

            /**
             * Sets the value of the foliofiscal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFoliofiscal(String value) {
                this.foliofiscal = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VehiculoUsadoEnajenadoPermAlFab"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="PrecioVehUsado" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_Importe" /&gt;
     *                 &lt;attribute name="TipoVeh" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_TipoVehiculo_s" /&gt;
     *                 &lt;attribute name="Marca" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="50"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="TipooClase" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="50"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Año" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                       &lt;minInclusive value="1900"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Modelo"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NIV"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="17"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumSerie"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="17"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumPlacas" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="10"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumMotor"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="17"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumFolTarjCir" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="40"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumFolAvisoint" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="20"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumPedIm" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="40"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Aduana" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="FechaRegulVeh" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                 &lt;attribute name="Foliofiscal" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="36"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="VehiculoNuvoSemEnajenadoFabAlPerm"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Año" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                       &lt;minInclusive value="1900"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Modelo"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="NumPlacas" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="10"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="RFC" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_RFC" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="VehEnaj" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_VehiculoEnajenado" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vehiculoUsadoEnajenadoPermAlFab",
        "vehiculoNuvoSemEnajenadoFabAlPerm"
    })
    public static class DecretoSustitVehicular
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "VehiculoUsadoEnajenadoPermAlFab", required = true)
        protected Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoUsadoEnajenadoPermAlFab vehiculoUsadoEnajenadoPermAlFab;
        @XmlElement(name = "VehiculoNuvoSemEnajenadoFabAlPerm", required = true)
        protected Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoNuvoSemEnajenadoFabAlPerm vehiculoNuvoSemEnajenadoFabAlPerm;
        @XmlAttribute(name = "VehEnaj", required = true)
        protected String vehEnaj;

        /**
         * Gets the value of the vehiculoUsadoEnajenadoPermAlFab property.
         * 
         * @return
         *     possible object is
         *     {@link Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoUsadoEnajenadoPermAlFab }
         *     
         */
        public Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoUsadoEnajenadoPermAlFab getVehiculoUsadoEnajenadoPermAlFab() {
            return vehiculoUsadoEnajenadoPermAlFab;
        }

        /**
         * Sets the value of the vehiculoUsadoEnajenadoPermAlFab property.
         * 
         * @param value
         *     allowed object is
         *     {@link Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoUsadoEnajenadoPermAlFab }
         *     
         */
        public void setVehiculoUsadoEnajenadoPermAlFab(Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoUsadoEnajenadoPermAlFab value) {
            this.vehiculoUsadoEnajenadoPermAlFab = value;
        }

        /**
         * Gets the value of the vehiculoNuvoSemEnajenadoFabAlPerm property.
         * 
         * @return
         *     possible object is
         *     {@link Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoNuvoSemEnajenadoFabAlPerm }
         *     
         */
        public Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoNuvoSemEnajenadoFabAlPerm getVehiculoNuvoSemEnajenadoFabAlPerm() {
            return vehiculoNuvoSemEnajenadoFabAlPerm;
        }

        /**
         * Sets the value of the vehiculoNuvoSemEnajenadoFabAlPerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoNuvoSemEnajenadoFabAlPerm }
         *     
         */
        public void setVehiculoNuvoSemEnajenadoFabAlPerm(Renovacionysustitucionvehiculos.DecretoSustitVehicular.VehiculoNuvoSemEnajenadoFabAlPerm value) {
            this.vehiculoNuvoSemEnajenadoFabAlPerm = value;
        }

        /**
         * Gets the value of the vehEnaj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVehEnaj() {
            return vehEnaj;
        }

        /**
         * Sets the value of the vehEnaj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVehEnaj(String value) {
            this.vehEnaj = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Año" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *             &lt;minInclusive value="1900"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Modelo"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumPlacas" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="10"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="RFC" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_RFC" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VehiculoNuvoSemEnajenadoFabAlPerm
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "A\u00f1o", required = true)
            protected int año;
            @XmlAttribute(name = "Modelo")
            protected String modelo;
            @XmlAttribute(name = "NumPlacas", required = true)
            protected String numPlacas;
            @XmlAttribute(name = "RFC")
            protected String rfc;

            /**
             * Gets the value of the año property.
             * 
             */
            public int getAño() {
                return año;
            }

            /**
             * Sets the value of the año property.
             * 
             */
            public void setAño(int value) {
                this.año = value;
            }

            /**
             * Gets the value of the modelo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModelo() {
                return modelo;
            }

            /**
             * Sets the value of the modelo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModelo(String value) {
                this.modelo = value;
            }

            /**
             * Gets the value of the numPlacas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumPlacas() {
                return numPlacas;
            }

            /**
             * Sets the value of the numPlacas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumPlacas(String value) {
                this.numPlacas = value;
            }

            /**
             * Gets the value of the rfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRFC() {
                return rfc;
            }

            /**
             * Sets the value of the rfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRFC(String value) {
                this.rfc = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="PrecioVehUsado" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}t_Importe" /&gt;
         *       &lt;attribute name="TipoVeh" use="required" type="{http://www.sat.gob.mx/renovacionysustitucionvehiculos}c_TipoVehiculo_s" /&gt;
         *       &lt;attribute name="Marca" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="50"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="TipooClase" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="50"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Año" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *             &lt;minInclusive value="1900"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Modelo"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NIV"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="17"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumSerie"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="17"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumPlacas" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="10"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumMotor"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="17"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumFolTarjCir" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="40"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumFolAvisoint" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="20"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="NumPedIm" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="40"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Aduana" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="FechaRegulVeh" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *       &lt;attribute name="Foliofiscal" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="36"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VehiculoUsadoEnajenadoPermAlFab
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "PrecioVehUsado", required = true)
            protected BigDecimal precioVehUsado;
            @XmlAttribute(name = "TipoVeh", required = true)
            protected String tipoVeh;
            @XmlAttribute(name = "Marca", required = true)
            protected String marca;
            @XmlAttribute(name = "TipooClase", required = true)
            protected String tipooClase;
            @XmlAttribute(name = "A\u00f1o", required = true)
            protected int año;
            @XmlAttribute(name = "Modelo")
            protected String modelo;
            @XmlAttribute(name = "NIV")
            protected String niv;
            @XmlAttribute(name = "NumSerie")
            protected String numSerie;
            @XmlAttribute(name = "NumPlacas", required = true)
            protected String numPlacas;
            @XmlAttribute(name = "NumMotor")
            protected String numMotor;
            @XmlAttribute(name = "NumFolTarjCir", required = true)
            protected String numFolTarjCir;
            @XmlAttribute(name = "NumFolAvisoint", required = true)
            protected String numFolAvisoint;
            @XmlAttribute(name = "NumPedIm", required = true)
            protected String numPedIm;
            @XmlAttribute(name = "Aduana", required = true)
            protected String aduana;
            @XmlAttribute(name = "FechaRegulVeh", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaRegulVeh;
            @XmlAttribute(name = "Foliofiscal", required = true)
            protected String foliofiscal;

            /**
             * Gets the value of the precioVehUsado property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPrecioVehUsado() {
                return precioVehUsado;
            }

            /**
             * Sets the value of the precioVehUsado property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPrecioVehUsado(BigDecimal value) {
                this.precioVehUsado = value;
            }

            /**
             * Gets the value of the tipoVeh property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoVeh() {
                return tipoVeh;
            }

            /**
             * Sets the value of the tipoVeh property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoVeh(String value) {
                this.tipoVeh = value;
            }

            /**
             * Gets the value of the marca property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMarca() {
                return marca;
            }

            /**
             * Sets the value of the marca property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMarca(String value) {
                this.marca = value;
            }

            /**
             * Gets the value of the tipooClase property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipooClase() {
                return tipooClase;
            }

            /**
             * Sets the value of the tipooClase property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipooClase(String value) {
                this.tipooClase = value;
            }

            /**
             * Gets the value of the año property.
             * 
             */
            public int getAño() {
                return año;
            }

            /**
             * Sets the value of the año property.
             * 
             */
            public void setAño(int value) {
                this.año = value;
            }

            /**
             * Gets the value of the modelo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModelo() {
                return modelo;
            }

            /**
             * Sets the value of the modelo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModelo(String value) {
                this.modelo = value;
            }

            /**
             * Gets the value of the niv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNIV() {
                return niv;
            }

            /**
             * Sets the value of the niv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNIV(String value) {
                this.niv = value;
            }

            /**
             * Gets the value of the numSerie property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumSerie() {
                return numSerie;
            }

            /**
             * Sets the value of the numSerie property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumSerie(String value) {
                this.numSerie = value;
            }

            /**
             * Gets the value of the numPlacas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumPlacas() {
                return numPlacas;
            }

            /**
             * Sets the value of the numPlacas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumPlacas(String value) {
                this.numPlacas = value;
            }

            /**
             * Gets the value of the numMotor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumMotor() {
                return numMotor;
            }

            /**
             * Sets the value of the numMotor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumMotor(String value) {
                this.numMotor = value;
            }

            /**
             * Gets the value of the numFolTarjCir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumFolTarjCir() {
                return numFolTarjCir;
            }

            /**
             * Sets the value of the numFolTarjCir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumFolTarjCir(String value) {
                this.numFolTarjCir = value;
            }

            /**
             * Gets the value of the numFolAvisoint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumFolAvisoint() {
                return numFolAvisoint;
            }

            /**
             * Sets the value of the numFolAvisoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumFolAvisoint(String value) {
                this.numFolAvisoint = value;
            }

            /**
             * Gets the value of the numPedIm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumPedIm() {
                return numPedIm;
            }

            /**
             * Sets the value of the numPedIm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumPedIm(String value) {
                this.numPedIm = value;
            }

            /**
             * Gets the value of the aduana property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAduana() {
                return aduana;
            }

            /**
             * Sets the value of the aduana property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAduana(String value) {
                this.aduana = value;
            }

            /**
             * Gets the value of the fechaRegulVeh property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFechaRegulVeh() {
                return fechaRegulVeh;
            }

            /**
             * Sets the value of the fechaRegulVeh property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFechaRegulVeh(XMLGregorianCalendar value) {
                this.fechaRegulVeh = value;
            }

            /**
             * Gets the value of the foliofiscal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFoliofiscal() {
                return foliofiscal;
            }

            /**
             * Sets the value of the foliofiscal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFoliofiscal(String value) {
                this.foliofiscal = value;
            }

        }

    }

}
