//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 11:47:57 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/registrofiscal", xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.sat.gob.mx/registrofiscal", prefix = "registrofiscal")
})
package mx.gob.sat.cfd.bindings.cfdiregistrofiscal;
