//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 11:48:02 PM CDT 
//


package mx.gob.sat.cfd.bindings.ecb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfd.bindings.ecb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfd.bindings.ecb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario }
     * 
     */
    public EstadoDeCuentaBancario createEstadoDeCuentaBancario() {
        return new EstadoDeCuentaBancario();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario.Movimientos }
     * 
     */
    public EstadoDeCuentaBancario.Movimientos createEstadoDeCuentaBancarioMovimientos() {
        return new EstadoDeCuentaBancario.Movimientos();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario.Movimientos.MovimientoECB }
     * 
     */
    public EstadoDeCuentaBancario.Movimientos.MovimientoECB createEstadoDeCuentaBancarioMovimientosMovimientoECB() {
        return new EstadoDeCuentaBancario.Movimientos.MovimientoECB();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario.Movimientos.MovimientoECBFiscal }
     * 
     */
    public EstadoDeCuentaBancario.Movimientos.MovimientoECBFiscal createEstadoDeCuentaBancarioMovimientosMovimientoECBFiscal() {
        return new EstadoDeCuentaBancario.Movimientos.MovimientoECBFiscal();
    }

}
