//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.25 at 03:58:19 PM CST 
//


package mx.gob.sat.cfd.bindings.IngresosHidrocarburos;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentoRelacionado" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="FolioFiscalVinculado" use="required"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;length value="36"/&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                       &lt;pattern value="[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="FechaFolioFiscalVinculado" use="required"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date"&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                       &lt;pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="Mes" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Meses" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Version" use="required" fixed="1.0"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;whiteSpace value="collapse"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="NumeroContrato" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="50"/&gt;
 *             &lt;whiteSpace value="collapse"/&gt;
 *             &lt;pattern value="[^|]{1,50}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ContraprestacionPagadaOperador" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *       &lt;attribute name="Porcentaje" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;fractionDigits value="3"/&gt;
 *             &lt;minInclusive value="0.001"/&gt;
 *             &lt;maxInclusive value="100.000"/&gt;
 *             &lt;whiteSpace value="collapse"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentoRelacionado"
})
@XmlRootElement(name = "IngresosHidrocarburos")
public class IngresosHidrocarburos
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DocumentoRelacionado", required = true)
    protected List<IngresosHidrocarburos.DocumentoRelacionado> documentoRelacionado;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "NumeroContrato", required = true)
    protected String numeroContrato;
    @XmlAttribute(name = "ContraprestacionPagadaOperador", required = true)
    protected BigDecimal contraprestacionPagadaOperador;
    @XmlAttribute(name = "Porcentaje", required = true)
    protected BigDecimal porcentaje;

    /**
     * Gets the value of the documentoRelacionado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentoRelacionado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentoRelacionado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IngresosHidrocarburos.DocumentoRelacionado }
     * 
     * 
     */
    public List<IngresosHidrocarburos.DocumentoRelacionado> getDocumentoRelacionado() {
        if (documentoRelacionado == null) {
            documentoRelacionado = new ArrayList<IngresosHidrocarburos.DocumentoRelacionado>();
        }
        return this.documentoRelacionado;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the numeroContrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroContrato() {
        return numeroContrato;
    }

    /**
     * Sets the value of the numeroContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroContrato(String value) {
        this.numeroContrato = value;
    }

    /**
     * Gets the value of the contraprestacionPagadaOperador property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getContraprestacionPagadaOperador() {
        return contraprestacionPagadaOperador;
    }

    /**
     * Sets the value of the contraprestacionPagadaOperador property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setContraprestacionPagadaOperador(BigDecimal value) {
        this.contraprestacionPagadaOperador = value;
    }

    /**
     * Gets the value of the porcentaje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPorcentaje() {
        return porcentaje;
    }

    /**
     * Sets the value of the porcentaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPorcentaje(BigDecimal value) {
        this.porcentaje = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="FolioFiscalVinculado" use="required"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;length value="36"/&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *             &lt;pattern value="[a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12}"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="FechaFolioFiscalVinculado" use="required"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date"&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *             &lt;pattern value="([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="Mes" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos}Meses" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DocumentoRelacionado
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute(name = "FolioFiscalVinculado", required = true)
        protected String folioFiscalVinculado;
        @XmlAttribute(name = "FechaFolioFiscalVinculado", required = true)
        protected XMLGregorianCalendar fechaFolioFiscalVinculado;
        @XmlAttribute(name = "Mes", required = true)
        protected String mes;

        /**
         * Gets the value of the folioFiscalVinculado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFolioFiscalVinculado() {
            return folioFiscalVinculado;
        }

        /**
         * Sets the value of the folioFiscalVinculado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFolioFiscalVinculado(String value) {
            this.folioFiscalVinculado = value;
        }

        /**
         * Gets the value of the fechaFolioFiscalVinculado property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaFolioFiscalVinculado() {
            return fechaFolioFiscalVinculado;
        }

        /**
         * Sets the value of the fechaFolioFiscalVinculado property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaFolioFiscalVinculado(XMLGregorianCalendar value) {
            this.fechaFolioFiscalVinculado = value;
        }

        /**
         * Gets the value of the mes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMes() {
            return mes;
        }

        /**
         * Sets the value of the mes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMes(String value) {
            this.mes = value;
        }

    }

}
