//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.10 at 11:14:03 PM CST 
//


package mx.gob.sat.cfd.bindings.CartaPorte20;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfd.bindings.CartaPorte20 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfd.bindings.CartaPorte20
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CartaPorte }
     * 
     */
    public CartaPorte createCartaPorte() {
        return new CartaPorte();
    }

    /**
     * Create an instance of {@link CartaPorte.FiguraTransporte }
     * 
     */
    public CartaPorte.FiguraTransporte createCartaPorteFiguraTransporte() {
        return new CartaPorte.FiguraTransporte();
    }

    /**
     * Create an instance of {@link CartaPorte.FiguraTransporte.TiposFigura }
     * 
     */
    public CartaPorte.FiguraTransporte.TiposFigura createCartaPorteFiguraTransporteTiposFigura() {
        return new CartaPorte.FiguraTransporte.TiposFigura();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias }
     * 
     */
    public CartaPorte.Mercancias createCartaPorteMercancias() {
        return new CartaPorte.Mercancias();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.TransporteFerroviario }
     * 
     */
    public CartaPorte.Mercancias.TransporteFerroviario createCartaPorteMercanciasTransporteFerroviario() {
        return new CartaPorte.Mercancias.TransporteFerroviario();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.TransporteFerroviario.Carro }
     * 
     */
    public CartaPorte.Mercancias.TransporteFerroviario.Carro createCartaPorteMercanciasTransporteFerroviarioCarro() {
        return new CartaPorte.Mercancias.TransporteFerroviario.Carro();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.TransporteMaritimo }
     * 
     */
    public CartaPorte.Mercancias.TransporteMaritimo createCartaPorteMercanciasTransporteMaritimo() {
        return new CartaPorte.Mercancias.TransporteMaritimo();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Autotransporte }
     * 
     */
    public CartaPorte.Mercancias.Autotransporte createCartaPorteMercanciasAutotransporte() {
        return new CartaPorte.Mercancias.Autotransporte();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Autotransporte.Remolques }
     * 
     */
    public CartaPorte.Mercancias.Autotransporte.Remolques createCartaPorteMercanciasAutotransporteRemolques() {
        return new CartaPorte.Mercancias.Autotransporte.Remolques();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Mercancia }
     * 
     */
    public CartaPorte.Mercancias.Mercancia createCartaPorteMercanciasMercancia() {
        return new CartaPorte.Mercancias.Mercancia();
    }

    /**
     * Create an instance of {@link CartaPorte.Ubicaciones }
     * 
     */
    public CartaPorte.Ubicaciones createCartaPorteUbicaciones() {
        return new CartaPorte.Ubicaciones();
    }

    /**
     * Create an instance of {@link CartaPorte.Ubicaciones.Ubicacion }
     * 
     */
    public CartaPorte.Ubicaciones.Ubicacion createCartaPorteUbicacionesUbicacion() {
        return new CartaPorte.Ubicaciones.Ubicacion();
    }

    /**
     * Create an instance of {@link CartaPorte.FiguraTransporte.TiposFigura.PartesTransporte }
     * 
     */
    public CartaPorte.FiguraTransporte.TiposFigura.PartesTransporte createCartaPorteFiguraTransporteTiposFiguraPartesTransporte() {
        return new CartaPorte.FiguraTransporte.TiposFigura.PartesTransporte();
    }

    /**
     * Create an instance of {@link CartaPorte.FiguraTransporte.TiposFigura.Domicilio }
     * 
     */
    public CartaPorte.FiguraTransporte.TiposFigura.Domicilio createCartaPorteFiguraTransporteTiposFiguraDomicilio() {
        return new CartaPorte.FiguraTransporte.TiposFigura.Domicilio();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.TransporteAereo }
     * 
     */
    public CartaPorte.Mercancias.TransporteAereo createCartaPorteMercanciasTransporteAereo() {
        return new CartaPorte.Mercancias.TransporteAereo();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.TransporteFerroviario.DerechosDePaso }
     * 
     */
    public CartaPorte.Mercancias.TransporteFerroviario.DerechosDePaso createCartaPorteMercanciasTransporteFerroviarioDerechosDePaso() {
        return new CartaPorte.Mercancias.TransporteFerroviario.DerechosDePaso();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.TransporteFerroviario.Carro.Contenedor }
     * 
     */
    public CartaPorte.Mercancias.TransporteFerroviario.Carro.Contenedor createCartaPorteMercanciasTransporteFerroviarioCarroContenedor() {
        return new CartaPorte.Mercancias.TransporteFerroviario.Carro.Contenedor();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.TransporteMaritimo.Contenedor }
     * 
     */
    public CartaPorte.Mercancias.TransporteMaritimo.Contenedor createCartaPorteMercanciasTransporteMaritimoContenedor() {
        return new CartaPorte.Mercancias.TransporteMaritimo.Contenedor();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Autotransporte.IdentificacionVehicular }
     * 
     */
    public CartaPorte.Mercancias.Autotransporte.IdentificacionVehicular createCartaPorteMercanciasAutotransporteIdentificacionVehicular() {
        return new CartaPorte.Mercancias.Autotransporte.IdentificacionVehicular();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Autotransporte.Seguros }
     * 
     */
    public CartaPorte.Mercancias.Autotransporte.Seguros createCartaPorteMercanciasAutotransporteSeguros() {
        return new CartaPorte.Mercancias.Autotransporte.Seguros();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Autotransporte.Remolques.Remolque }
     * 
     */
    public CartaPorte.Mercancias.Autotransporte.Remolques.Remolque createCartaPorteMercanciasAutotransporteRemolquesRemolque() {
        return new CartaPorte.Mercancias.Autotransporte.Remolques.Remolque();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Mercancia.Pedimentos }
     * 
     */
    public CartaPorte.Mercancias.Mercancia.Pedimentos createCartaPorteMercanciasMercanciaPedimentos() {
        return new CartaPorte.Mercancias.Mercancia.Pedimentos();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Mercancia.GuiasIdentificacion }
     * 
     */
    public CartaPorte.Mercancias.Mercancia.GuiasIdentificacion createCartaPorteMercanciasMercanciaGuiasIdentificacion() {
        return new CartaPorte.Mercancias.Mercancia.GuiasIdentificacion();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Mercancia.CantidadTransporta }
     * 
     */
    public CartaPorte.Mercancias.Mercancia.CantidadTransporta createCartaPorteMercanciasMercanciaCantidadTransporta() {
        return new CartaPorte.Mercancias.Mercancia.CantidadTransporta();
    }

    /**
     * Create an instance of {@link CartaPorte.Mercancias.Mercancia.DetalleMercancia }
     * 
     */
    public CartaPorte.Mercancias.Mercancia.DetalleMercancia createCartaPorteMercanciasMercanciaDetalleMercancia() {
        return new CartaPorte.Mercancias.Mercancia.DetalleMercancia();
    }

    /**
     * Create an instance of {@link CartaPorte.Ubicaciones.Ubicacion.Domicilio }
     * 
     */
    public CartaPorte.Ubicaciones.Ubicacion.Domicilio createCartaPorteUbicacionesUbicacionDomicilio() {
        return new CartaPorte.Ubicaciones.Ubicacion.Domicilio();
    }

}
