//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.15 at 02:39:03 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/divisas", xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.sat.gob.mx/divisas", prefix = "divisas")
})
package mx.gob.sat.cfd.bindings.divisas;
