//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.10 at 11:14:17 PM CST 
//


package mx.gob.sat.cfd.bindings.Pagos10;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Pago" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DoctoRelacionado" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="IdDocumento" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="16"/&gt;
 *                                 &lt;maxLength value="36"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                                 &lt;pattern value="([a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12})|([0-9]{3}-[0-9]{2}-[0-9]{9})"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Serie"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="25"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                                 &lt;pattern value="[^|]{1,25}"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="Folio"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="40"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                                 &lt;pattern value="[^|]{1,40}"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="MonedaDR" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Moneda" /&gt;
 *                           &lt;attribute name="TipoCambioDR"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                                 &lt;fractionDigits value="6"/&gt;
 *                                 &lt;minInclusive value="0.000001"/&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="MetodoDePagoDR" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_MetodoPago" /&gt;
 *                           &lt;attribute name="NumParcialidad"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                                 &lt;whiteSpace value="collapse"/&gt;
 *                                 &lt;pattern value="[1-9][0-9]{0,2}"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="ImpSaldoAnt" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                           &lt;attribute name="ImpPagado" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                           &lt;attribute name="ImpSaldoInsoluto" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Impuestos" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Retenciones" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Retencion" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
 *                                               &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Traslados" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Traslado" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
 *                                               &lt;attribute name="TipoFactor" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_TipoFactor" /&gt;
 *                                               &lt;attribute name="TasaOCuota" use="required"&gt;
 *                                                 &lt;simpleType&gt;
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                                                     &lt;fractionDigits value="6"/&gt;
 *                                                     &lt;minInclusive value="0.000000"/&gt;
 *                                                     &lt;whiteSpace value="collapse"/&gt;
 *                                                   &lt;/restriction&gt;
 *                                                 &lt;/simpleType&gt;
 *                                               &lt;/attribute&gt;
 *                                               &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="TotalImpuestosRetenidos" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                           &lt;attribute name="TotalImpuestosTrasladados" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="FechaPago" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_FechaH" /&gt;
 *                 &lt;attribute name="FormaDePagoP" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_FormaPago" /&gt;
 *                 &lt;attribute name="MonedaP" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Moneda" /&gt;
 *                 &lt;attribute name="TipoCambioP"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                       &lt;fractionDigits value="6"/&gt;
 *                       &lt;minInclusive value="0.000001"/&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="Monto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
 *                 &lt;attribute name="NumOperacion"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="1"/&gt;
 *                       &lt;maxLength value="100"/&gt;
 *                       &lt;pattern value="[^|]{1,100}"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="RfcEmisorCtaOrd"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="12"/&gt;
 *                       &lt;maxLength value="13"/&gt;
 *                       &lt;pattern value="XEXX010101000|[A-Z&amp;Ñ]{3}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]"/&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="NomBancoOrdExt"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="1"/&gt;
 *                       &lt;maxLength value="300"/&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                       &lt;pattern value="[^|]{1,300}"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="CtaOrdenante"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="10"/&gt;
 *                       &lt;maxLength value="50"/&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                       &lt;pattern value="[A-Z0-9_]{10,50}"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="RfcEmisorCtaBen" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_RFC_PM" /&gt;
 *                 &lt;attribute name="CtaBeneficiario"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="10"/&gt;
 *                       &lt;maxLength value="50"/&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                       &lt;pattern value="[A-Z0-9_]{10,50}"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="TipoCadPago" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos}c_TipoCadenaPago" /&gt;
 *                 &lt;attribute name="CertPago"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary"&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="CadPago"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;minLength value="1"/&gt;
 *                       &lt;maxLength value="8192"/&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="SelloPago"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary"&gt;
 *                       &lt;whiteSpace value="collapse"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Version" use="required" fixed="1.0"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;whiteSpace value="collapse"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pago"
})
@XmlRootElement(name = "Pagos")
public class Pagos
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Pago", required = true)
    protected List<Pagos.Pago> pago;
    @XmlAttribute(name = "Version", required = true)
    protected String version;

    /**
     * Gets the value of the pago property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pago property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPago().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pagos.Pago }
     * 
     * 
     */
    public List<Pagos.Pago> getPago() {
        if (pago == null) {
            pago = new ArrayList<Pagos.Pago>();
        }
        return this.pago;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DoctoRelacionado" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="IdDocumento" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="16"/&gt;
     *                       &lt;maxLength value="36"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                       &lt;pattern value="([a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12})|([0-9]{3}-[0-9]{2}-[0-9]{9})"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Serie"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="25"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                       &lt;pattern value="[^|]{1,25}"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="Folio"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;minLength value="1"/&gt;
     *                       &lt;maxLength value="40"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                       &lt;pattern value="[^|]{1,40}"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="MonedaDR" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Moneda" /&gt;
     *                 &lt;attribute name="TipoCambioDR"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *                       &lt;fractionDigits value="6"/&gt;
     *                       &lt;minInclusive value="0.000001"/&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="MetodoDePagoDR" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_MetodoPago" /&gt;
     *                 &lt;attribute name="NumParcialidad"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
     *                       &lt;whiteSpace value="collapse"/&gt;
     *                       &lt;pattern value="[1-9][0-9]{0,2}"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="ImpSaldoAnt" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *                 &lt;attribute name="ImpPagado" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *                 &lt;attribute name="ImpSaldoInsoluto" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Impuestos" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Retenciones" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Retencion" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
     *                                     &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Traslados" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Traslado" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
     *                                     &lt;attribute name="TipoFactor" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_TipoFactor" /&gt;
     *                                     &lt;attribute name="TasaOCuota" use="required"&gt;
     *                                       &lt;simpleType&gt;
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *                                           &lt;fractionDigits value="6"/&gt;
     *                                           &lt;minInclusive value="0.000000"/&gt;
     *                                           &lt;whiteSpace value="collapse"/&gt;
     *                                         &lt;/restriction&gt;
     *                                       &lt;/simpleType&gt;
     *                                     &lt;/attribute&gt;
     *                                     &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="TotalImpuestosRetenidos" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *                 &lt;attribute name="TotalImpuestosTrasladados" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="FechaPago" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_FechaH" /&gt;
     *       &lt;attribute name="FormaDePagoP" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_FormaPago" /&gt;
     *       &lt;attribute name="MonedaP" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Moneda" /&gt;
     *       &lt;attribute name="TipoCambioP"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *             &lt;fractionDigits value="6"/&gt;
     *             &lt;minInclusive value="0.000001"/&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="Monto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
     *       &lt;attribute name="NumOperacion"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="1"/&gt;
     *             &lt;maxLength value="100"/&gt;
     *             &lt;pattern value="[^|]{1,100}"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="RfcEmisorCtaOrd"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="12"/&gt;
     *             &lt;maxLength value="13"/&gt;
     *             &lt;pattern value="XEXX010101000|[A-Z&amp;Ñ]{3}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]"/&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="NomBancoOrdExt"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="1"/&gt;
     *             &lt;maxLength value="300"/&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *             &lt;pattern value="[^|]{1,300}"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="CtaOrdenante"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="10"/&gt;
     *             &lt;maxLength value="50"/&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *             &lt;pattern value="[A-Z0-9_]{10,50}"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="RfcEmisorCtaBen" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_RFC_PM" /&gt;
     *       &lt;attribute name="CtaBeneficiario"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="10"/&gt;
     *             &lt;maxLength value="50"/&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *             &lt;pattern value="[A-Z0-9_]{10,50}"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="TipoCadPago" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos}c_TipoCadenaPago" /&gt;
     *       &lt;attribute name="CertPago"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary"&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="CadPago"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="1"/&gt;
     *             &lt;maxLength value="8192"/&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="SelloPago"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary"&gt;
     *             &lt;whiteSpace value="collapse"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "doctoRelacionado",
        "impuestos"
    })
    public static class Pago
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "DoctoRelacionado")
        protected List<Pagos.Pago.DoctoRelacionado> doctoRelacionado;
        @XmlElement(name = "Impuestos")
        protected List<Pagos.Pago.Impuestos> impuestos;
        @XmlAttribute(name = "FechaPago", required = true)
        protected XMLGregorianCalendar fechaPago;
        @XmlAttribute(name = "FormaDePagoP", required = true)
        protected String formaDePagoP;
        @XmlAttribute(name = "MonedaP", required = true)
        protected String monedaP;
        @XmlAttribute(name = "TipoCambioP")
        protected BigDecimal tipoCambioP;
        @XmlAttribute(name = "Monto", required = true)
        protected BigDecimal monto;
        @XmlAttribute(name = "NumOperacion")
        protected String numOperacion;
        @XmlAttribute(name = "RfcEmisorCtaOrd")
        protected String rfcEmisorCtaOrd;
        @XmlAttribute(name = "NomBancoOrdExt")
        protected String nomBancoOrdExt;
        @XmlAttribute(name = "CtaOrdenante")
        protected String ctaOrdenante;
        @XmlAttribute(name = "RfcEmisorCtaBen")
        protected String rfcEmisorCtaBen;
        @XmlAttribute(name = "CtaBeneficiario")
        protected String ctaBeneficiario;
        @XmlAttribute(name = "TipoCadPago")
        protected String tipoCadPago;
        @XmlAttribute(name = "CertPago")
        protected byte[] certPago;
        @XmlAttribute(name = "CadPago")
        protected String cadPago;
        @XmlAttribute(name = "SelloPago")
        protected byte[] selloPago;

        /**
         * Gets the value of the doctoRelacionado property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the doctoRelacionado property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDoctoRelacionado().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Pagos.Pago.DoctoRelacionado }
         * 
         * 
         */
        public List<Pagos.Pago.DoctoRelacionado> getDoctoRelacionado() {
            if (doctoRelacionado == null) {
                doctoRelacionado = new ArrayList<Pagos.Pago.DoctoRelacionado>();
            }
            return this.doctoRelacionado;
        }

        /**
         * Gets the value of the impuestos property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the impuestos property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImpuestos().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Pagos.Pago.Impuestos }
         * 
         * 
         */
        public List<Pagos.Pago.Impuestos> getImpuestos() {
            if (impuestos == null) {
                impuestos = new ArrayList<Pagos.Pago.Impuestos>();
            }
            return this.impuestos;
        }

        /**
         * Gets the value of the fechaPago property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaPago() {
            return fechaPago;
        }

        /**
         * Sets the value of the fechaPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaPago(XMLGregorianCalendar value) {
            this.fechaPago = value;
        }

        /**
         * Gets the value of the formaDePagoP property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormaDePagoP() {
            return formaDePagoP;
        }

        /**
         * Sets the value of the formaDePagoP property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormaDePagoP(String value) {
            this.formaDePagoP = value;
        }

        /**
         * Gets the value of the monedaP property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonedaP() {
            return monedaP;
        }

        /**
         * Sets the value of the monedaP property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonedaP(String value) {
            this.monedaP = value;
        }

        /**
         * Gets the value of the tipoCambioP property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTipoCambioP() {
            return tipoCambioP;
        }

        /**
         * Sets the value of the tipoCambioP property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTipoCambioP(BigDecimal value) {
            this.tipoCambioP = value;
        }

        /**
         * Gets the value of the monto property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMonto() {
            return monto;
        }

        /**
         * Sets the value of the monto property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMonto(BigDecimal value) {
            this.monto = value;
        }

        /**
         * Gets the value of the numOperacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumOperacion() {
            return numOperacion;
        }

        /**
         * Sets the value of the numOperacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumOperacion(String value) {
            this.numOperacion = value;
        }

        /**
         * Gets the value of the rfcEmisorCtaOrd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRfcEmisorCtaOrd() {
            return rfcEmisorCtaOrd;
        }

        /**
         * Sets the value of the rfcEmisorCtaOrd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRfcEmisorCtaOrd(String value) {
            this.rfcEmisorCtaOrd = value;
        }

        /**
         * Gets the value of the nomBancoOrdExt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNomBancoOrdExt() {
            return nomBancoOrdExt;
        }

        /**
         * Sets the value of the nomBancoOrdExt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNomBancoOrdExt(String value) {
            this.nomBancoOrdExt = value;
        }

        /**
         * Gets the value of the ctaOrdenante property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCtaOrdenante() {
            return ctaOrdenante;
        }

        /**
         * Sets the value of the ctaOrdenante property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCtaOrdenante(String value) {
            this.ctaOrdenante = value;
        }

        /**
         * Gets the value of the rfcEmisorCtaBen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRfcEmisorCtaBen() {
            return rfcEmisorCtaBen;
        }

        /**
         * Sets the value of the rfcEmisorCtaBen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRfcEmisorCtaBen(String value) {
            this.rfcEmisorCtaBen = value;
        }

        /**
         * Gets the value of the ctaBeneficiario property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCtaBeneficiario() {
            return ctaBeneficiario;
        }

        /**
         * Sets the value of the ctaBeneficiario property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCtaBeneficiario(String value) {
            this.ctaBeneficiario = value;
        }

        /**
         * Gets the value of the tipoCadPago property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoCadPago() {
            return tipoCadPago;
        }

        /**
         * Sets the value of the tipoCadPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoCadPago(String value) {
            this.tipoCadPago = value;
        }

        /**
         * Gets the value of the certPago property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getCertPago() {
            return certPago;
        }

        /**
         * Sets the value of the certPago property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setCertPago(byte[] value) {
            this.certPago = value;
        }

        /**
         * Gets the value of the cadPago property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCadPago() {
            return cadPago;
        }

        /**
         * Sets the value of the cadPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCadPago(String value) {
            this.cadPago = value;
        }

        /**
         * Gets the value of the selloPago property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getSelloPago() {
            return selloPago;
        }

        /**
         * Sets the value of the selloPago property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setSelloPago(byte[] value) {
            this.selloPago = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="IdDocumento" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="16"/&gt;
         *             &lt;maxLength value="36"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *             &lt;pattern value="([a-f0-9A-F]{8}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{4}-[a-f0-9A-F]{12})|([0-9]{3}-[0-9]{2}-[0-9]{9})"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Serie"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="25"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *             &lt;pattern value="[^|]{1,25}"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="Folio"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="40"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *             &lt;pattern value="[^|]{1,40}"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="MonedaDR" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Moneda" /&gt;
         *       &lt;attribute name="TipoCambioDR"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
         *             &lt;fractionDigits value="6"/&gt;
         *             &lt;minInclusive value="0.000001"/&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="MetodoDePagoDR" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_MetodoPago" /&gt;
         *       &lt;attribute name="NumParcialidad"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
         *             &lt;whiteSpace value="collapse"/&gt;
         *             &lt;pattern value="[1-9][0-9]{0,2}"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="ImpSaldoAnt" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
         *       &lt;attribute name="ImpPagado" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
         *       &lt;attribute name="ImpSaldoInsoluto" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DoctoRelacionado
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "IdDocumento", required = true)
            protected String idDocumento;
            @XmlAttribute(name = "Serie")
            protected String serie;
            @XmlAttribute(name = "Folio")
            protected String folio;
            @XmlAttribute(name = "MonedaDR", required = true)
            protected String monedaDR;
            @XmlAttribute(name = "TipoCambioDR")
            protected BigDecimal tipoCambioDR;
            @XmlAttribute(name = "MetodoDePagoDR", required = true)
            protected String metodoDePagoDR;
            @XmlAttribute(name = "NumParcialidad")
            protected BigInteger numParcialidad;
            @XmlAttribute(name = "ImpSaldoAnt")
            protected BigDecimal impSaldoAnt;
            @XmlAttribute(name = "ImpPagado")
            protected BigDecimal impPagado;
            @XmlAttribute(name = "ImpSaldoInsoluto")
            protected BigDecimal impSaldoInsoluto;

            /**
             * Gets the value of the idDocumento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdDocumento() {
                return idDocumento;
            }

            /**
             * Sets the value of the idDocumento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdDocumento(String value) {
                this.idDocumento = value;
            }

            /**
             * Gets the value of the serie property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSerie() {
                return serie;
            }

            /**
             * Sets the value of the serie property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSerie(String value) {
                this.serie = value;
            }

            /**
             * Gets the value of the folio property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFolio() {
                return folio;
            }

            /**
             * Sets the value of the folio property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFolio(String value) {
                this.folio = value;
            }

            /**
             * Gets the value of the monedaDR property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMonedaDR() {
                return monedaDR;
            }

            /**
             * Sets the value of the monedaDR property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMonedaDR(String value) {
                this.monedaDR = value;
            }

            /**
             * Gets the value of the tipoCambioDR property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTipoCambioDR() {
                return tipoCambioDR;
            }

            /**
             * Sets the value of the tipoCambioDR property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTipoCambioDR(BigDecimal value) {
                this.tipoCambioDR = value;
            }

            /**
             * Gets the value of the metodoDePagoDR property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMetodoDePagoDR() {
                return metodoDePagoDR;
            }

            /**
             * Sets the value of the metodoDePagoDR property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMetodoDePagoDR(String value) {
                this.metodoDePagoDR = value;
            }

            /**
             * Gets the value of the numParcialidad property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumParcialidad() {
                return numParcialidad;
            }

            /**
             * Sets the value of the numParcialidad property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumParcialidad(BigInteger value) {
                this.numParcialidad = value;
            }

            /**
             * Gets the value of the impSaldoAnt property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImpSaldoAnt() {
                return impSaldoAnt;
            }

            /**
             * Sets the value of the impSaldoAnt property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImpSaldoAnt(BigDecimal value) {
                this.impSaldoAnt = value;
            }

            /**
             * Gets the value of the impPagado property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImpPagado() {
                return impPagado;
            }

            /**
             * Sets the value of the impPagado property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImpPagado(BigDecimal value) {
                this.impPagado = value;
            }

            /**
             * Gets the value of the impSaldoInsoluto property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImpSaldoInsoluto() {
                return impSaldoInsoluto;
            }

            /**
             * Sets the value of the impSaldoInsoluto property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImpSaldoInsoluto(BigDecimal value) {
                this.impSaldoInsoluto = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Retenciones" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Retencion" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
         *                           &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Traslados" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Traslado" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
         *                           &lt;attribute name="TipoFactor" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_TipoFactor" /&gt;
         *                           &lt;attribute name="TasaOCuota" use="required"&gt;
         *                             &lt;simpleType&gt;
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
         *                                 &lt;fractionDigits value="6"/&gt;
         *                                 &lt;minInclusive value="0.000000"/&gt;
         *                                 &lt;whiteSpace value="collapse"/&gt;
         *                               &lt;/restriction&gt;
         *                             &lt;/simpleType&gt;
         *                           &lt;/attribute&gt;
         *                           &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="TotalImpuestosRetenidos" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
         *       &lt;attribute name="TotalImpuestosTrasladados" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "retenciones",
            "traslados"
        })
        public static class Impuestos
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "Retenciones")
            protected Pagos.Pago.Impuestos.Retenciones retenciones;
            @XmlElement(name = "Traslados")
            protected Pagos.Pago.Impuestos.Traslados traslados;
            @XmlAttribute(name = "TotalImpuestosRetenidos")
            protected BigDecimal totalImpuestosRetenidos;
            @XmlAttribute(name = "TotalImpuestosTrasladados")
            protected BigDecimal totalImpuestosTrasladados;

            /**
             * Gets the value of the retenciones property.
             * 
             * @return
             *     possible object is
             *     {@link Pagos.Pago.Impuestos.Retenciones }
             *     
             */
            public Pagos.Pago.Impuestos.Retenciones getRetenciones() {
                return retenciones;
            }

            /**
             * Sets the value of the retenciones property.
             * 
             * @param value
             *     allowed object is
             *     {@link Pagos.Pago.Impuestos.Retenciones }
             *     
             */
            public void setRetenciones(Pagos.Pago.Impuestos.Retenciones value) {
                this.retenciones = value;
            }

            /**
             * Gets the value of the traslados property.
             * 
             * @return
             *     possible object is
             *     {@link Pagos.Pago.Impuestos.Traslados }
             *     
             */
            public Pagos.Pago.Impuestos.Traslados getTraslados() {
                return traslados;
            }

            /**
             * Sets the value of the traslados property.
             * 
             * @param value
             *     allowed object is
             *     {@link Pagos.Pago.Impuestos.Traslados }
             *     
             */
            public void setTraslados(Pagos.Pago.Impuestos.Traslados value) {
                this.traslados = value;
            }

            /**
             * Gets the value of the totalImpuestosRetenidos property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotalImpuestosRetenidos() {
                return totalImpuestosRetenidos;
            }

            /**
             * Sets the value of the totalImpuestosRetenidos property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotalImpuestosRetenidos(BigDecimal value) {
                this.totalImpuestosRetenidos = value;
            }

            /**
             * Gets the value of the totalImpuestosTrasladados property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotalImpuestosTrasladados() {
                return totalImpuestosTrasladados;
            }

            /**
             * Sets the value of the totalImpuestosTrasladados property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotalImpuestosTrasladados(BigDecimal value) {
                this.totalImpuestosTrasladados = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Retencion" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
             *                 &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "retencion"
            })
            public static class Retenciones
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "Retencion", required = true)
                protected List<Pagos.Pago.Impuestos.Retenciones.Retencion> retencion;

                /**
                 * Gets the value of the retencion property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the retencion property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getRetencion().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Pagos.Pago.Impuestos.Retenciones.Retencion }
                 * 
                 * 
                 */
                public List<Pagos.Pago.Impuestos.Retenciones.Retencion> getRetencion() {
                    if (retencion == null) {
                        retencion = new ArrayList<Pagos.Pago.Impuestos.Retenciones.Retencion>();
                    }
                    return this.retencion;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
                 *       &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Retencion
                    implements Serializable
                {

                    private final static long serialVersionUID = 1L;
                    @XmlAttribute(name = "Impuesto", required = true)
                    protected String impuesto;
                    @XmlAttribute(name = "Importe", required = true)
                    protected BigDecimal importe;

                    /**
                     * Gets the value of the impuesto property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getImpuesto() {
                        return impuesto;
                    }

                    /**
                     * Sets the value of the impuesto property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setImpuesto(String value) {
                        this.impuesto = value;
                    }

                    /**
                     * Gets the value of the importe property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getImporte() {
                        return importe;
                    }

                    /**
                     * Sets the value of the importe property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setImporte(BigDecimal value) {
                        this.importe = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Traslado" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
             *                 &lt;attribute name="TipoFactor" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_TipoFactor" /&gt;
             *                 &lt;attribute name="TasaOCuota" use="required"&gt;
             *                   &lt;simpleType&gt;
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
             *                       &lt;fractionDigits value="6"/&gt;
             *                       &lt;minInclusive value="0.000000"/&gt;
             *                       &lt;whiteSpace value="collapse"/&gt;
             *                     &lt;/restriction&gt;
             *                   &lt;/simpleType&gt;
             *                 &lt;/attribute&gt;
             *                 &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "traslado"
            })
            public static class Traslados
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "Traslado", required = true)
                protected List<Pagos.Pago.Impuestos.Traslados.Traslado> traslado;

                /**
                 * Gets the value of the traslado property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the traslado property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTraslado().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Pagos.Pago.Impuestos.Traslados.Traslado }
                 * 
                 * 
                 */
                public List<Pagos.Pago.Impuestos.Traslados.Traslado> getTraslado() {
                    if (traslado == null) {
                        traslado = new ArrayList<Pagos.Pago.Impuestos.Traslados.Traslado>();
                    }
                    return this.traslado;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;attribute name="Impuesto" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_Impuesto" /&gt;
                 *       &lt;attribute name="TipoFactor" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/catalogos}c_TipoFactor" /&gt;
                 *       &lt;attribute name="TasaOCuota" use="required"&gt;
                 *         &lt;simpleType&gt;
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
                 *             &lt;fractionDigits value="6"/&gt;
                 *             &lt;minInclusive value="0.000000"/&gt;
                 *             &lt;whiteSpace value="collapse"/&gt;
                 *           &lt;/restriction&gt;
                 *         &lt;/simpleType&gt;
                 *       &lt;/attribute&gt;
                 *       &lt;attribute name="Importe" use="required" type="{http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI}t_Importe" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Traslado
                    implements Serializable
                {

                    private final static long serialVersionUID = 1L;
                    @XmlAttribute(name = "Impuesto", required = true)
                    protected String impuesto;
                    @XmlAttribute(name = "TipoFactor", required = true)
                    protected String tipoFactor;
                    @XmlAttribute(name = "TasaOCuota", required = true)
                    protected BigDecimal tasaOCuota;
                    @XmlAttribute(name = "Importe", required = true)
                    protected BigDecimal importe;

                    /**
                     * Gets the value of the impuesto property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getImpuesto() {
                        return impuesto;
                    }

                    /**
                     * Sets the value of the impuesto property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setImpuesto(String value) {
                        this.impuesto = value;
                    }

                    /**
                     * Gets the value of the tipoFactor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTipoFactor() {
                        return tipoFactor;
                    }

                    /**
                     * Sets the value of the tipoFactor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTipoFactor(String value) {
                        this.tipoFactor = value;
                    }

                    /**
                     * Gets the value of the tasaOCuota property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getTasaOCuota() {
                        return tasaOCuota;
                    }

                    /**
                     * Sets the value of the tasaOCuota property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setTasaOCuota(BigDecimal value) {
                        this.tasaOCuota = value;
                    }

                    /**
                     * Gets the value of the importe property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getImporte() {
                        return importe;
                    }

                    /**
                     * Sets the value of the importe property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setImporte(BigDecimal value) {
                        this.importe = value;
                    }

                }

            }

        }

    }

}
