//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.15 at 02:38:49 PM CST 
//


package mx.gob.sat.cfd.bindings.aerolineas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.cfd.bindings.aerolineas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.cfd.bindings.aerolineas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aerolineas }
     * 
     */
    public Aerolineas createAerolineas() {
        return new Aerolineas();
    }

    /**
     * Create an instance of {@link Aerolineas.OtrosCargos }
     * 
     */
    public Aerolineas.OtrosCargos createAerolineasOtrosCargos() {
        return new Aerolineas.OtrosCargos();
    }

    /**
     * Create an instance of {@link Aerolineas.OtrosCargos.Cargo }
     * 
     */
    public Aerolineas.OtrosCargos.Cargo createAerolineasOtrosCargosCargo() {
        return new Aerolineas.OtrosCargos.Cargo();
    }

}
